services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-pv-fe
    container_name: web-pv-fe
    restart: unless-stopped
    env_file: .env
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
