version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-pv-fe
    container_name: web-pv-fe
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - VITE_NODE_ENV=$VITE_NODE_ENV
      - VITE_API_URL=$VITE_API_URL
      - VITE_API_KEY=$VITE_API_KEY
      - VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
      - VITE_PROJECT_ID=$VITE_PROJECT_ID
      - VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
      - VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
      - VITE_APP_ID=$VITE_APP_ID
      - VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID
      - VITE_X_API_KEY_SECRET=$VITE_X_API_KEY_SECRET
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
